FEATURES_WITHOUT_PC = 6
PC_LENGTH = 32
FEATURES = FEATURES_WITHOUT_PC + PC_LENGTH

EPOCHS = 2
EPOCHS_SIZE = 500

ENCODER_IN_SIZE = 8
ENCODER_OUT_SIZE = 5
DECODER_IN_SIZE = 3
DECODER_OUT_SIZE = ENCODER_OUT_SIZE

MAX_INST_IN_WINDOW = 8
NOT_NEEDED_FEATURES = 4

WINDOWS_NUMBER = 50862